[[project]]
path = ""
version = "0.10.0"
assembler = "gas"
instruction_set = "x86"

[project.opts]
compiler = "i686-elf-gcc"
compile_flags_txt = [
    "-Wall",
    "-Wextra",
    "-pedantic",
    "-ffreestanding",
    "-nostdlib",
	"-Iinclude/"
]
diagnostics = true
default_diagnostics = false
